dashboar
Okazaki92/Codeholics-Wallet-App pull request #22
Opened 2023-09-27 16:19 UTC by HannaRogalska

2023-09-27 16:38 UTC, Okazaki92 requested changes
Małą poprawka :)

2023-09-27 16:38 UTC, Okazaki92 commented on src/index.css
> +}
root css jest w pliku variables.css w folderze stylesheet. To jeśli możesz to proszę przerzuć to tam, sprawdź czy się nie duplikują i stamtąd wyciągaj :)

2023-09-27 19:05 UTC, Okazaki92 requested changes
A więc folder z componentami zmień dashboard na Dashboard itd, do tego navMenu możesz usunąć i wykorzystać komponent Navigation bo tam jest już całą nawigacja zrobiona więc nie musisz jej ponownie pisać., Zmiany stron opakuj w Outlet żeby nie odświażało strony pokażdej zmianie.  Do tego w folderze transactions w pliku TransactionTableDesk brakuje prop-types.
W pliku TransactionDesk w exporcie jest <p className={styles.transactionText}>w środku masz takie coś {" "} <== do czego to służy? Przepraszam, że tyle do roboty teraz się zrobiło ale na pewno sobie poradzisz. W razie czego daj znać :D

2023-09-30 19:57 UTC, closed without merging

2023-09-30 19:59 UTC, HannaRogalska commented
Przetrze to wszystko było zmienione z parę dni temu?

Сб, 30.09.2023 в 21:57, Vincent Słomiński ***@***.***>:

> Closed #22 <https://github.com/Okazaki92/Codeholics-Wallet-App/pull/22>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Okazaki92/Codeholics-Wallet-App/pull/22#event-10517921178>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A266GUXXW4FN34J343D6XOTX5B2RRANCNFSM6AAAAAA5JT6XIY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>