poprawka login form
Okazaki92/Codeholics-Wallet-App pull request #25
Opened 2023-09-27 19:51 UTC by DagmaraSobczak

2023-09-27 20:09 UTC, Okazaki92 requested changes
na slacku przesłałem kod żeby login działał i przekierowywał na register oraz na home

2023-09-28 18:20 UTC, DagmaraSobczak commented
znowu to samo, pokazuje, że mam konflikt a ja właśnie to chce zmienić <<<<<<< login-poprawka
          <Route path="/login" element={<LoginPage />} />
=======
          <Route
            path="/login"
            element={
              <RestrictedRoute redirectTo="/register" element={<LoginPage />} />
            }
          />
>>>>>>> main

2023-09-28 20:30 UTC, Okazaki92 requested changes

2023-09-28 20:30 UTC, Okazaki92 commented on src/components/LoginForm/LoginForm.jsx
> +        navigate("/homepage");
tu nie powinno być /home?

2023-09-29 18:13 UTC, Okazaki92 approved these changes
Jest OK :D

2023-09-29 18:13 UTC, merged